name: Build Hybrid SkyHawk Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip binwalk cpio gzip lz4 tar xz-utils unzip
        pip install gdown

    - name: Prepare working directory
      run: mkdir -p work

    - name: Download SkyHawk and Extreme TWRP from Google Drive
      working-directory: work
      run: |
        gdown --id 1mFfJwMXXEcDYf9yiJ87LKmsbmRNSKpgF -O skyhawk.img
        gdown --id 1mG-6qnmANWZCdJEOMDEHvD5-wCVVLhCU -O extreme.tar

    - name: Extract Extreme TWRP files
      working-directory: work
      run: |
        mkdir extreme
        tar -xf extreme.tar -C extreme

    - name: Extract SkyHawk ramdisk using binwalk
      working-directory: work
      run: |
        mkdir extracted
        binwalk --extract --directory extracted skyhawk.img

        RAMDISK=$(find extracted -type f -name '*.cpio*' | head -n 1)
        if [ -z "$RAMDISK" ]; then
          echo "Failed to detect compressed ramdisk!"
          exit 1
        fi
        cp "$RAMDISK" ramdisk.cpio
        mkdir ramdisk
        cd ramdisk
        cpio -idm < ../ramdisk.cpio

    - name: Inject Extreme compatibility files
      working-directory: work
      run: |
        cp extreme/recovery.fstab ramdisk/etc/recovery.fstab || true
        cp extreme/init.rc ramdisk/init.rc || true
        echo "Injection complete."

    - name: Repack hybrid image with SkyHawk header
      working-directory: work
      run: |
        # Extract SkyHawk header
        dd if=skyhawk.img of=header bs=1 count=2048
        cd ramdisk
        find . | cpio -o -H newc | gzip > ../new-ramdisk.gz
        cd ..
        cat header new-ramdisk.gz > recovery-hybrid.img
        mv recovery-hybrid.img $GITHUB_WORKSPACE/

    - name: Upload recovery image to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SkyHawk-Hybrid-Recovery
        path: recovery-hybrid.img
