name: Build SkyHawk Hybrid Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y p7zip-full cpio binwalk unzip curl gzip lz4 android-sdk-libsparse-utils

    - name: Download recovery images
      run: |
        mkdir input
        curl -L -o input/extreme.img 'https://drive.google.com/uc?id=1mFfJwMXXEcDYf9yiJ87LKmsbmRNSKpgF&export=download'
        curl -L -o input/skyhawk.zip 'https://drive.google.com/uc?id=1mKfk43jlNCBMh9jgFHejYAmML2-RYrss&export=download'

    - name: Extract SkyHawk ZIP
      run: |
        mkdir skyhawk_zip
        unzip input/skyhawk.zip -d skyhawk_zip
        find skyhawk_zip -name "*.img" -exec mv {} skyhawk.img \;

    - name: Extract SkyHawk Ramdisk
      run: |
        mkdir extracted_skyhawk
        binwalk --extract --directory extracted_skyhawk skyhawk.img
        RAMDISK=$(find extracted_skyhawk -type f -name '*.cpio*' | head -n 1)
        if [ -z "$RAMDISK" ]; then echo "SkyHawk ramdisk not found"; exit 1; fi
        cp "$RAMDISK" skyhawk_ramdisk.cpio
        mkdir skyhawk_ramdisk
        cd skyhawk_ramdisk
        cpio -idm < ../skyhawk_ramdisk.cpio

    - name: Extract Extreme Ramdisk
      run: |
        mkdir extracted_extreme
        binwalk --extract --directory extracted_extreme input/extreme.img
        RAMDISK=$(find extracted_extreme -type f -name '*.cpio*' | head -n 1)
        if [ -z "$RAMDISK" ]; then echo "Extreme ramdisk not found"; exit 1; fi
        cp "$RAMDISK" extreme_ramdisk.cpio
        mkdir extreme_ramdisk
        cd extreme_ramdisk
        cpio -idm < ../extreme_ramdisk.cpio

    - name: Merge Extreme files into SkyHawk
      run: |
        cp -r extreme_ramdisk/sbin skyhawk_ramdisk/ || true
        cp -r extreme_ramdisk/res/* skyhawk_ramdisk/res/ || true
        cp -a extreme_ramdisk/*.rc skyhawk_ramdisk/ || true
        cp -a extreme_ramdisk/*.prop skyhawk_ramdisk/ || true
        cp -a extreme_ramdisk/fstab* skyhawk_ramdisk/ || true

    - name: Repack new hybrid recovery
      run: |
        cd skyhawk_ramdisk
        find . | cpio -o -H newc | gzip > ../hybrid_ramdisk.cpio.gz
        cd ..
        mkdir out
        mkbootimg \
          --kernel extracted_skyhawk/skyhawk.img.extracted/zImage \
          --ramdisk hybrid_ramdisk.cpio.gz \
          --base 0x10000000 \
          --pagesize 2048 \
          --cmdline "androidboot.hardware=exynos9820 console=ttyS0,115200n8" \
          -o out/skyhawk_hybrid.img
        7z a out/skyhawk_hybrid.7z out/skyhawk_hybrid.img

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/skyhawk_hybrid.7z
        tag_name: hybrid-${{ github.run_number }}
        name: SkyHawk Hybrid Build ${{ github.run_number }}
        body: |
          SkyHawk Hybrid recovery with Extreme ROM compatibility patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
