name: Build SkyHawk Hybrid Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip cpio gzip lz4 tar
        pip install gdown

    - name: Download input files from Google Drive
      run: |
        mkdir -p work
        cd work
        # Download SkyHawk image
        gdown --id 1mFfJwMXXEcDYf9yiJ87LKmsbmRNSKpgF -O skyhawk.img
        # Download Extreme TWRP OdinPack
        gdown --id 1mG-6qnmANWZCdJEOMDEHvD5-wCVVLhCU -O extreme.tar

    - name: Extract Extreme TWRP
      run: |
        cd work
        mkdir extreme
        tar -xf extreme.tar -C extreme

    - name: Extract SkyHawk ramdisk
      run: |
        cd work
        dd if=skyhawk.img of=header bs=1 count=2048
        dd if=skyhawk.img of=ramdisk.gz bs=1 skip=2048
        gzip -d ramdisk.gz
        mkdir ramdisk
        cd ramdisk
        cpio -idm < ../ramdisk

    - name: Inject Extreme compatibility files
      run: |
        cp work/extreme/recovery.fstab work/ramdisk/etc/recovery.fstab || true
        cp work/extreme/init.rc work/ramdisk/init.rc || true

    - name: Repack recovery
      run: |
        cd work/ramdisk
        find . | cpio -o -H newc | gzip > ../new-ramdisk.gz
        cd ..
        cat header new-ramdisk.gz > recovery-hybrid.img
        mv recovery-hybrid.img $GITHUB_WORKSPACE/

    - name: Upload Hybrid Recovery
      uses: actions/upload-artifact@v4
      with:
        name: SkyHawk-Hybrid-Recovery
        path: recovery-hybrid.img
