name: SkyHawk Hybrid Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Set up tools
      run: |
        sudo apt update
        sudo apt install -y p7zip-full cpio binwalk unzip curl gzip lz4 android-sdk-libsparse-utils

    - name: Download recovery images from Google Drive
      run: |
        mkdir input
        curl -L -o input/extreme.img 'https://drive.google.com/uc?id=1mFfJwMXXEcDYf9yiJ87LKmsbmRNSKpgF&export=download'
        curl -L -o input/skyhawk.zip 'https://drive.google.com/uc?id=1mG-6qnmANWZCdJEOMDEHvD5-wCVVLhCU&export=download'

    - name: Extract SkyHawk ZIP
      run: |
        mkdir -p skyhawk_zip
        unzip input/skyhawk.zip -d skyhawk_zip
        mv skyhawk_zip/recovery.img skyhawk.img

    - name: Extract SkyHawk Ramdisk
      run: |
        mkdir extracted_skyhawk
        binwalk --extract --directory extracted_skyhawk skyhawk.img

        RAMDISK=$(find extracted_skyhawk -type f -name '*.cpio*' | head -n 1)
        if [ -z "$RAMDISK" ]; then
          echo "Failed to detect compressed SkyHawk ramdisk!"
          exit 1
        fi
        cp "$RAMDISK" skyhawk_ramdisk.cpio
        mkdir skyhawk_ramdisk
        cd skyhawk_ramdisk
        cpio -idm < ../skyhawk_ramdisk.cpio

    - name: Extract Extreme TWRP Ramdisk
      run: |
        mkdir extracted_extreme
        binwalk --extract --directory extracted_extreme input/extreme.img

        RAMDISK=$(find extracted_extreme -type f -name '*.cpio*' | head -n 1)
        if [ -z "$RAMDISK" ]; then
          echo "Failed to detect Extreme ramdisk!"
          exit 1
        fi
        cp "$RAMDISK" extreme_ramdisk.cpio
        mkdir extreme_ramdisk
        cd extreme_ramdisk
        cpio -idm < ../extreme_ramdisk.cpio

    - name: Merge Compatibility from Extreme
      run: |
        cp -r extreme_ramdisk/sbin skyhawk_ramdisk/
        cp -r extreme_ramdisk/res/* skyhawk_ramdisk/res/ || true
        cp -a extreme_ramdisk/*.rc skyhawk_ramdisk/
        cp -a extreme_ramdisk/*.prop skyhawk_ramdisk/
        cp -a extreme_ramdisk/fstab* skyhawk_ramdisk/ || true

    - name: Repack and Compress Image
      run: |
        cd skyhawk_ramdisk
        find . | cpio -o -H newc | gzip > ../hybrid_ramdisk.cpio.gz
        cd ..
        mkdir out
        mkbootimg \
          --kernel extracted_skyhawk/skyhawk.img.extracted/zImage \
          --ramdisk hybrid_ramdisk.cpio.gz \
          --base 0x10000000 \
          --pagesize 2048 \
          --cmdline "androidboot.hardware=exynos9820 console=ttyS0,115200n8" \
          -o out/hybrid_skyhawk.img

        7z a out/hybrid_skyhawk.7z out/hybrid_skyhawk.img

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/hybrid_skyhawk.7z
        tag_name: skyhawk-hybrid-${{ github.run_number }}
        name: SkyHawk Hybrid Build ${{ github.run_number }}
        body: |
          SkyHawk Hybrid Recovery (based on your files from Google Drive).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
