name: Build SkyHawk Hybrid Recovery (IMG-only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y p7zip-full cpio binwalk gzip lz4 android-sdk-libsparse-utils

    - name: Download recovery images
      run: |
        mkdir input
        curl -L -o input/extreme.img 'https://drive.google.com/uc?id=1mFfJwMXXEcDYf9yiJ87LKmsbmRNSKpgF&export=download'
        curl -L -o input/skyhawk.img 'https://drive.google.com/uc?id=1mKfk43jlNCBMh9jgFHejYAmML2-RYrss&export=download'

    - name: Extract SkyHawk recovery
      run: |
        mkdir extracted_skyhawk
        binwalk --extract --directory extracted_skyhawk input/skyhawk.img
        SKYHAWK_RAMDISK=$(find extracted_skyhawk -type f -name '*.cpio*' | head -n 1)
        mkdir skyhawk_ramdisk
        cd skyhawk_ramdisk
        cpio -idm < "$GITHUB_WORKSPACE/$SKYHAWK_RAMDISK"

    - name: Extract Extreme recovery
      run: |
        mkdir extracted_extreme
        binwalk --extract --directory extracted_extreme input/extreme.img
        EXTREME_RAMDISK=$(find extracted_extreme -type f -name '*.cpio*' | head -n 1)
        mkdir extreme_ramdisk
        cd extreme_ramdisk
        cpio -idm < "$GITHUB_WORKSPACE/$EXTREME_RAMDISK"

    - name: Inject Extreme compatibility
      run: |
        cp -r extreme_ramdisk/sbin/* skyhawk_ramdisk/sbin/ || true
        cp -r extreme_ramdisk/res/* skyhawk_ramdisk/res/ || true
        cp -a extreme_ramdisk/*.rc skyhawk_ramdisk/ || true
        cp -a extreme_ramdisk/*.prop skyhawk_ramdisk/ || true
        cp -a extreme_ramdisk/fstab* skyhawk_ramdisk/ || true

    - name: Repack hybrid image
      run: |
        cd skyhawk_ramdisk
        find . | cpio -o -H newc | gzip > ../hybrid_ramdisk.cpio.gz
        cd ..
        mkdir out
        mkbootimg \
          --kernel extracted_skyhawk/input.skyhawk.img.extracted/zImage \
          --ramdisk hybrid_ramdisk.cpio.gz \
          --base 0x10000000 \
          --pagesize 2048 \
          --cmdline "androidboot.hardware=exynos9820 console=ttyS0,115200n8" \
          -o out/skyhawk_hybrid.img
        7z a out/skyhawk_hybrid.7z out/skyhawk_hybrid.img

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/skyhawk_hybrid.7z
        tag_name: hybrid-${{ github.run_number }}
        name: SkyHawk Hybrid Build ${{ github.run_number }}
        body: |
          Hybrid SkyHawk recovery using Extreme compatibility layer.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
